# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5814d2e42b205282771474371bddb82e79570241668a985c8b29c702213b1c6d928889c8f98a3863ccaf45b9f2f67b596327a842ba52057caa77b9b83a09b79e

test:
  secret_key_base: 85019c086272ee2a2ecfd7347a87eab7b565a2b64722000661214c1e31c76f2b528bfca0bbec25bafda599ecf9dcf4ff66582e37e44283196926aab764686a7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
